// <auto-generated />
namespace TimeTidy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddTimeSheets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTimeSheets));
        
        string IMigrationMetadata.Id
        {
            get { return "201701231057581_AddTimeSheets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
